version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      # merged and released instantly
      sec-updates:
        applies-to: security-updates
        patterns:
          - "*"
      # merged automatically
      dev-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      # merged and released instantly
      sec-updates:
        applies-to: security-updates
        patterns:
          - "*"
      # merged automatically
      dev-dependencies:
        patterns:
          # gradle plugins
          - "*ktlint-gradle"
          - "*dokka-gradle-plugin"
          - "*kover-gradle-plugin"
          - "*publish-plugin"
          - "*maven-plugin"
          - "*java-gradle-plugin"
          - "*gradle-integration-test-plugin"
          # test dependencies
          - "org.assertj*"
          - "org.junit*"
      # merged and released automatically
      prod-dependencies:
        update-types:
          - "patch"
          - "minor"
      # requires human approval and has higher chance to fail build
      prod-dependencies-major:
        update-types:
          - "major"
