name: Release Auto

on:
  workflow_dispatch:
    inputs:
      security-updates-only:
        description: "Security updates only"
        type: boolean
        required: false
        default: false
      consider-snapshot:
        description: "Consider snapshot"
        type: boolean
        required: false
        default: false
  workflow_run:
    workflows: ["Build"]
    types: [completed]
    branches:
      - main
      - v*x.x
  schedule:
    # at 5:30 UTC every other month
    - cron: "30 5 1 */2 *"

jobs:
  check:
    uses: coditory/workflows/.github/workflows/release-auto-check.yml@v1
    secrets: inherit
    with:
      security-updates-only: ${{ inputs.security-updates-only || github.event_name == 'workflow_run' }}

  release:
    uses: ./.github/workflows/release.yml
    secrets: inherit
    if: needs.check.outputs.release == 'true'
    needs: check
